<?
$keywords_data=[
    /*
    'url'=>[
                'value'=>'Каталог',
                '_active'=>true,
            ],            
    */
    '/catalog'=>[
                'value'=>'Каталог',
                '_active'=>false,
                ],
];
?>