<?
$title_data=[
    /*
    'url'=>[
        'value'=>'name',
        '_postscr'=>true,
        '_postscr_id'=>'',
        //'_postscr_value'=>false,
    ],
    'url'=>['name'],
    */
    '/catalog'=>[
        'value'=>'Каталог',
        '_postscr'=>false,
        '_postscr_id'=>'',
    ],
    '/catalog/podcatalog'=>['Каталог'],
        
];
?>